CREATE OR REPLACE VIEW `ci-datalake-dev.ci_dtlk_bqd_access_dev.VW_QUIMIOTERAPIA_ESQUEMAS_SESION_TAREAS` AS

/* ========================== KPI 9: PREESCRITOS ========================== */

SELECT

  -- FLAG DE KPI -- 
  'KPI9_PREESCRITOS' AS KPI_NOMBRE,

  --CAMPOS DE FECHA_DT GLOBALES
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO))                                   AS FECHA_DT,
  EXTRACT(YEAR  FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO)))               AS ANIO,
  EXTRACT(MONTH FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO)))               AS MES,
  FORMAT_DATE('%Y-%m', SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO)))             AS ANIO_MES,

  --PROTOCOLO
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO))                                   AS FECHA_INICIO_PROTOCOLO_DT,
  -- SESION
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA))                                           AS FECHA_PREVISTA_DT,
  -- TAREA
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_HORA_INICIO))                                        AS FECHA_HORA_INICIO_DT,

  -- KEY (CONTEO POR EL CUAL SE VA RALIZAR EL COUNT DISTINC - DEPENDE DEL KPI)

  CAST(HOJA_PROT_PK AS STRING) AS KEY,
  CAST(NULL AS STRING)         AS NUM_KEY,                            -- no aplica para este KPI


  -- COLUMNAS ADICIONALES DE INTERES
  -- PROTOCOLO
  CAST(HOJA_PROT_PK AS STRING)         AS HOJA_PROT_PK,
  TRIM(DIAGNOSTICO)                    AS DIAGNOSTICO_PROTOCOLO,
  TRIM(CAST(CODIGO_CLIENTE AS STRING)) AS CODIGO_CLIENTE_PROTOCOLO,
  TRIM(NOMBRE_ESQUEMA_TERAPEUTICO)     AS NOMBRE_ESQUEMA_TERAPEUTICO,
  TRIM(ESTADO_PROTOCOLO)               AS ESTADO_PROTOCOLO,
  -- CICLO - SESION
  CAST(PRES_SESION_CAB_PK AS STRING)   AS PRES_SESION_CAB_PK,
  TRIM(ESTADO_SESION)                  AS ESTADO_SESION,
  TRIM(ESTADO_SESION)                  AS TIEMPO_ESTIMADO,
  -- TAREA
  TRIM(ESTADO_TAREA)                   AS ESTADO_TAREA,
  

  /* ===== FILTROS PRESTACIONALES / DIMENSIONES ===== */
  NUM_ENCUENTRO,
  COD_PACIENTE,
  NOM_PACIENTE,
  NOM_APELL_PATERNO_PCTE,
  NOM_APELL_MATERNO_PCTE,
  NOM_COMPLETO,
  FECHA_ATENCION,
  COD_GRUPO_ESPECIALIDAD,
  DES_GRUPO_ESPECIALIDAD,
  COD_SERVICIO,
  DES_SERVICIO,
  COD_TIPO_CITA,
  DES_TIPO_CITA,
  COD_ORIGEN_ATENCION,
  DES_ORIGEN_ATENCION,
  COD_MOTIVO_ING_ENC,
  DES_MOTIVO_ING_ENC,
  COD_UNIDAD_NEGOCIO,
  DES_UNIDAD_NEGOCIO,
  AMBITO_HOMOLOGADO,
  COD_DIAGNOSTICO_01,
  DES_DIAGNOSTICO_01,
  COD_DIAGNOSTICO_02,
  DES_DIAGNOSTICO_02,
  COD_DIAGNOSTICO_03,
  DES_DIAGNOSTICO_03,
  COD_MEDICO,
  NOM_MEDICO,
  NOM_SEDE,
  EDAD_HOMOLOGADA,
  RANGO_ETARIO,
  RANGO_ETARIO_10_ANIOS,
  FH_ULTIMA_ACTUALIZACION
FROM `ci-datalake-dev.ci_dtlk_bqd_access_dev.TBL_ONCO_PROTOCOLO_PREFACTURA`
WHERE 
  TRIM(ESTADO_PROTOCOLO)  = 'Planificado'
  --AND TRIM(AMBITO_HOMOLOGADO) = 'Ambulatorio'
  AND HOJA_PROT_PK IS NOT NULL
  AND SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO)) IS NOT NULL

UNION ALL

/* ======================== KPI 10: ADMINISTRADOS ========================= */

SELECT
  -- FLAG DE KPI -- 
  'KPI10_ADMINISTRADOS' AS KPI_NOMBRE,

  --CAMPOS DE FECHA_DT GLOBALES
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA))                                         AS FECHA_DT,
  EXTRACT(YEAR  FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                     AS ANIO,
  EXTRACT(MONTH FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                     AS MES,
  FORMAT_DATE('%Y-%m', SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                   AS ANIO_MES,

  --PROTOCOLO
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO))                                   AS FECHA_INICIO_PROTOCOLO_DT,
  -- SESION
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA))                                           AS FECHA_PREVISTA_DT,
  -- TAREA
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_HORA_INICIO))                                        AS FECHA_HORA_INICIO_DT,

  -- KEY (CONTEO POR EL CUAL SE VA RALIZAR EL COUNT DISTINC - DEPENDE DEL KPI)
  CAST(PRES_SESION_CAB_PK AS STRING) AS KEY,
  CAST(NULL AS STRING)               AS NUM_KEY,                        -- no aplica

   -- COLUMNAS ADICIONALES DE INTERES
  -- PROTOCOLO
  CAST(HOJA_PROT_PK AS STRING)         AS HOJA_PROT_PK,
  TRIM(DIAGNOSTICO)                    AS DIAGNOSTICO_PROTOCOLO,
  TRIM(CAST(CODIGO_CLIENTE AS STRING)) AS CODIGO_CLIENTE_PROTOCOLO,
  TRIM(NOMBRE_ESQUEMA_TERAPEUTICO)     AS NOMBRE_ESQUEMA_TERAPEUTICO,
  TRIM(ESTADO_PROTOCOLO)               AS ESTADO_PROTOCOLO,
  -- CICLO - SESION
  CAST(PRES_SESION_CAB_PK AS STRING)   AS PRES_SESION_CAB_PK,
  TRIM(ESTADO_SESION)                  AS ESTADO_SESION,
  TRIM(ESTADO_SESION)                  AS TIEMPO_ESTIMADO,
  -- TAREA
  TRIM(ESTADO_TAREA)                   AS ESTADO_TAREA,
  


  /* ===== FILTROS PRESTACIONALES / DIMENSIONES ===== */
  NUM_ENCUENTRO,
  COD_PACIENTE,
  NOM_PACIENTE,
  NOM_APELL_PATERNO_PCTE,
  NOM_APELL_MATERNO_PCTE,
  NOM_COMPLETO,
  FECHA_ATENCION,
  COD_GRUPO_ESPECIALIDAD,
  DES_GRUPO_ESPECIALIDAD,
  COD_SERVICIO,
  DES_SERVICIO,
  COD_TIPO_CITA,
  DES_TIPO_CITA,
  COD_ORIGEN_ATENCION,
  DES_ORIGEN_ATENCION,
  COD_MOTIVO_ING_ENC,
  DES_MOTIVO_ING_ENC,
  COD_UNIDAD_NEGOCIO,
  DES_UNIDAD_NEGOCIO,
  AMBITO_HOMOLOGADO,
  COD_DIAGNOSTICO_01,
  DES_DIAGNOSTICO_01,
  COD_DIAGNOSTICO_02,
  DES_DIAGNOSTICO_02,
  COD_DIAGNOSTICO_03,
  DES_DIAGNOSTICO_03,
  COD_MEDICO,
  NOM_MEDICO,
  NOM_SEDE,
  EDAD_HOMOLOGADA,
  RANGO_ETARIO,
  RANGO_ETARIO_10_ANIOS,
  FH_ULTIMA_ACTUALIZACION
FROM `ci-datalake-dev.ci_dtlk_bqd_access_dev.TBL_ONCO_PROTOCOLO_PREFACTURA`
WHERE TRIM(AMBITO_HOMOLOGADO) = 'Ambulatorio'
  AND TRIM(ESTADO_SESION)     = 'Realizada'
  AND PRES_SESION_CAB_PK IS NOT NULL
  AND SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)) IS NOT NULL

UNION ALL

/* = KPI 11: % ADMINISTRADOS SEGÚN PLANIFICACIÓN ========================= */

SELECT
  -- FLAG DE KPI -- 
  'KPI11_PCT_PLAN' AS KPI_NOMBRE,

  --CAMPOS DE FECHA_DT GLOBALES
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA))                                         AS FECHA_DT,
  EXTRACT(YEAR  FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                     AS ANIO,
  EXTRACT(MONTH FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                     AS MES,
  FORMAT_DATE('%Y-%m', SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                   AS ANIO_MES,

    --PROTOCOLO
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO))                                   AS FECHA_INICIO_PROTOCOLO_DT,
  -- SESION
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA))                                           AS FECHA_PREVISTA_DT,
  -- TAREA
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_HORA_INICIO))                                        AS FECHA_HORA_INICIO_DT,

  -- KEY (COUNT DISTINC - PARA ESTE KPI FUNCIONA COMO DENOMINADOR)
  -- DETALLE: EN looker agregar CAMPO CALULADO: DENOMINADOR: COUNT_DISTINCT(KEY) o tambien COUNT_DISTINCT(PRES_SESION_CAB_PK)
  CAST(PRES_SESION_CAB_PK AS STRING) AS KEY,   

  -- NUM_KEY: COUNT DISTINC - PARA ESTE KPI FUNCIONA COMO NUMERADOR 
  -- DETALLE: EN looker agregar CAMPO CALULADO: NUMERADOR: COUNT_DISTINCT(NUM_KEY) 
  IF(
    TRIM(ESTADO_SESION) = 'Realizada'
    AND DATE(SAFE.PARSE_DATETIME('%d/%m/%Y %H:%M:%S', TRIM(FECHA_HORA_INICIO))) =
        SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)),
    CAST(PRES_SESION_CAB_PK AS STRING), NULL
  ) AS NUM_KEY,

  -------------------------------------
  -- En caso de este KPI para hallar el porcentraje crear un cmapo calculado en looker
  -- detalle campo calcualdor: KPI11 = COUNT_DISTINCT(NUM_KEY) / COUNT_DISTINCT(KEY)
  -------------------------------------

  -- COLUMNAS ADICIONALES DE INTERES

  -- PROTOCOLO
  CAST(HOJA_PROT_PK AS STRING)         AS HOJA_PROT_PK,
  TRIM(DIAGNOSTICO)                    AS DIAGNOSTICO_PROTOCOLO,
  TRIM(CAST(CODIGO_CLIENTE AS STRING)) AS CODIGO_CLIENTE_PROTOCOLO,
  TRIM(NOMBRE_ESQUEMA_TERAPEUTICO)     AS NOMBRE_ESQUEMA_TERAPEUTICO,
  TRIM(ESTADO_PROTOCOLO)               AS ESTADO_PROTOCOLO,
  -- CICLO - SESION
  CAST(PRES_SESION_CAB_PK AS STRING)   AS PRES_SESION_CAB_PK,
  TRIM(ESTADO_SESION)                  AS ESTADO_SESION,
  TRIM(ESTADO_SESION)                  AS TIEMPO_ESTIMADO,
  -- TAREA
  TRIM(ESTADO_TAREA)                   AS ESTADO_TAREA,
  
  /* ===== FILTROS PRESTACIONALES / DIMENSIONES ===== */
  NUM_ENCUENTRO,
  COD_PACIENTE,
  NOM_PACIENTE,
  NOM_APELL_PATERNO_PCTE,
  NOM_APELL_MATERNO_PCTE,
  NOM_COMPLETO,
  FECHA_ATENCION,
  COD_GRUPO_ESPECIALIDAD,
  DES_GRUPO_ESPECIALIDAD,
  COD_SERVICIO,
  DES_SERVICIO,
  COD_TIPO_CITA,
  DES_TIPO_CITA,
  COD_ORIGEN_ATENCION,
  DES_ORIGEN_ATENCION,
  COD_MOTIVO_ING_ENC,
  DES_MOTIVO_ING_ENC,
  COD_UNIDAD_NEGOCIO,
  DES_UNIDAD_NEGOCIO,
  AMBITO_HOMOLOGADO,  -- No proviene de Formulario sino de DES_UNIDAD_NEGOCIO
  COD_DIAGNOSTICO_01,
  DES_DIAGNOSTICO_01,
  COD_DIAGNOSTICO_02,
  DES_DIAGNOSTICO_02,
  COD_DIAGNOSTICO_03,
  DES_DIAGNOSTICO_03,
  COD_MEDICO,
  NOM_MEDICO,
  NOM_SEDE,
  EDAD_HOMOLOGADA,
  RANGO_ETARIO,
  RANGO_ETARIO_10_ANIOS,
  FH_ULTIMA_ACTUALIZACION
FROM `ci-datalake-dev.ci_dtlk_bqd_access_dev.TBL_ONCO_PROTOCOLO_PREFACTURA`
WHERE 
  SAFE_CAST(TRIM(CAST(NRO_TAREA AS STRING)) AS INT64) = 1
  AND  TRIM(ESTADO_SESION) = 'Realizada'
  AND TRIM(ESTADO_TAREA)   = 'Realizado'
  --AND TRIM(AMBITO_HOMOLOGADO)  = 'Ambulatorio'
  AND PRES_SESION_CAB_PK IS NOT NULL
  AND SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)) IS NOT NULL
;
