CREATE OR REPLACE TABLE `ci-datalake-dev.ci_dtlk_bqd_access_dev.TBL_ONCO_PROTOCOLO_PREFACTURA` AS
WITH base AS (
  SELECT
    -- =======================
    -- Campos SCRIPTS PROTOCOLOS - CICLO SESIONES - TAREAS
    -- =======================
    -- Protocolo
    onco.HOJA_PROT_PK,
    onco.CODIGO_CLIENTE,
    onco.ENCUENTRO_PROTOCOLO                           AS ENCUENTRO_PROTOCOLO,
    onco.CODIGO_PROTOCOLO,
    onco.PROTOCOLO,
    onco.CODIGO_DIAGNOSTICO,
    onco.DIAGNOSTICO,
    onco.ESTADO_PROTOCOLO                              AS ESTADO_PROTOCOLO,
    onco.FECHA_INICIO_PROTOCOLO                        AS FECHA_INICIO_PROTOCOLO,
    onco.FECHA_FIN_PROTOCOLO                           AS FECHA_FIN_PROTOCOLO,
    onco.FECHA_HORA_REGISTRO,

    -- Sesión
    onco.PRES_CICLO_PK,
    onco.CICLO,
    onco.PRES_SESION_CAB_PK,
    onco.NUMERO_SESION,
    onco.ENCUENTRO_SESION                              AS ENCUENTRO_SESION,
    onco.ESTADO_SESION,
    onco.DESTINO,
    onco.RECURSO,
    onco.TIEMPO_ESTIMADO,
    onco.FECHA_PREVISTA,
    onco.FECHA_HORA_PROGRAMADA,

    -- Tarea
    onco.PRES_SESION_DET_PK,
    onco.NRO_TAREA,
    onco.TAREA,
    onco.TIPO_TAREA,
    onco.DURACION,
    onco.ESTADO_TAREA,
    onco.FECHA_HORA_RECEP_FARMACIA,
    onco.FECHA_HORA_INICIO,
    onco.FECHA_HORA_FIN,
    onco.FECHA_HORA_DEVOL_FARMACIA,
    onco.OBSERVACIONES,

    -- Normalización del encuentro - paso adicional se  puede borrar
    SAFE_CAST(REGEXP_REPLACE(TRIM(CAST(onco.ENCUENTRO_PROTOCOLO AS STRING)), r'[^0-9]', '') AS INT64) AS encuentro_norm
  FROM `ci-datalake-dev.ci_dtlk_bqd_access_dev.TBL_ONCOLOGIA_PROTOCOLO_SESION_TAREA_BASE` onco
),
prefa AS (
  SELECT
    -- Encuentro
    CAST(PRE.NUM_ENCUENTRO AS STRING) AS NUM_ENCUENTRO,

    -- Paciente
    CAST(PRE.COD_PACIENTE AS STRING) AS COD_PACIENTE,
    PRE.NOM_PACIENTE,
    PRE.NOM_APELL_PATERNO_PCTE,
    PRE.NOM_APELL_MATERNO_PCTE,

    -- Nombre completo
    CONCAT(
      COALESCE(TRIM(PRE.NOM_PACIENTE), ''), ' ',
      COALESCE(TRIM(PRE.NOM_APELL_PATERNO_PCTE), ''), ' ',
      COALESCE(TRIM(PRE.NOM_APELL_MATERNO_PCTE), '')
    ) AS NOM_COMPLETO,

    -- Fecha de atención (texto dd/mm/yyyy)
    FORMAT_TIMESTAMP('%d/%m/%Y', PRE.FEH_PREFACTURA) AS FECHA_ATENCION,
    -- Fecha de atención como TIMESTAMP para cálculo de edad
    PRE.FEH_PREFACTURA AS FECHA_ATENCION_TS,

    -- Grupo especialidad
    PRE.COD_GRUPO_ESPECIALIDAD,
    PRE.DES_GRUPO_ESPECIALIDAD,

    -- Servicio
    PRE.COD_ESPECIALIDAD AS COD_SERVICIO,
    PRE.DES_ESPECIALIDAD AS DES_SERVICIO,

    -- Campos adicionales tomados en cuenta de tablas prestacional
    PRE.COD_TIPO_CITA,
    PRE.DES_TIPO_CITA,
    PRE.COD_ORIGEN_ATENCION,
    PRE.DES_ORIGEN_ATENCION,
    PRE.COD_MOTIVO_ING_ENC,
    PRE.DES_MOTIVO_ING_ENC,
    PRE.COD_UNIDAD_NEGOCIO,
    PRE.DES_UNIDAD_NEGOCIO,
    PRE.COD_DIAGNOSTICO_01,
    PRE.DES_DIAGNOSTICO_01,
    PRE.COD_DIAGNOSTICO_02,
    PRE.DES_DIAGNOSTICO_02,
    PRE.COD_DIAGNOSTICO_03,
    PRE.DES_DIAGNOSTICO_03,

    -- Médico - Campos adicionales tomados en cuenta de tablas prestacional
    PRE.COD_MEDICO,
    PRE.NOM_MEDICO,

    -- Sede - Campos adicionales tomados en cuenta de tablas prestacional
    PRE.COD_SEDE,
    PRE.NOM_SEDE,

    -- Normalización del encuentro - paso adicional se  puede borrar
    SAFE_CAST(REGEXP_REPLACE(TRIM(CAST(PRE.NUM_ENCUENTRO AS STRING)), r'[^0-9]', '') AS INT64) AS num_enc_norm
  FROM `ci-datalake-prod.ci_dtlk_bqd_staging_prod.OD_PREFACTURA` PRE
),
clientes AS (
  SELECT
    CAST(a.CODIGO_CLIENTE AS STRING) AS CODIGO_CLIENTE,
    a.NAC_FECHA, -- TIMESTAMP, p.e. '1965-11-02 00:00:00 UTC'
    CASE WHEN c.CODIGO_SEXO = 2 THEN 'MASCULINO'
              WHEN c.CODIGO_SEXO = 3 THEN 'FEMENINO'
              ELSE 'Sin Dato' END SEXO
  FROM `ci-datalake-prod.ci_dtlk_bqd_access_prod.xhis6_CLIENTES_acc` a
   LEFT JOIN `ci-datalake-prod.ci_dtlk_bqd_access_prod.xhis6_SEXO_acc` c ON a.CODIGO_SEXO = c.CODIGO_SEXO

),

-- UNION PRINCIPAL + cálculo de EDAD_HOMOLOGADA y AMBITO
joined AS (
  SELECT
    b.*,
    p.* EXCEPT(num_enc_norm), -- dejamos FECHA_ATENCION (formateada) para calcuilo de edad y ocultamos el TS en esta proyección
    --p.* EXCEPT(num_enc_norm, FECHA_ATENCION_TS), -- dejamos FECHA_ATENCION (formateada) para calcuilo de edad y ocultamos el TS en esta proyección
    -- AMBITO homologado ( DES_UNIDAD_NEGOCIO)
    c.SEXO,
    CASE
      WHEN UPPER(TRIM(p.DES_UNIDAD_NEGOCIO)) LIKE '%AMBULATORIO%' THEN 'Ambulatorio'
      WHEN UPPER(TRIM(p.DES_UNIDAD_NEGOCIO)) LIKE '%HOSPITAL%'    THEN 'Hospitalario'
      ELSE 'OTRO AMBITO'
    END AS AMBITO_HOMOLOGADO,
    -- EDAD_HOMOLOGADA: años cumplidos a la fecha de atención
    CASE
      WHEN c.NAC_FECHA IS NULL THEN NULL
      ELSE DATE_DIFF(DATE(p.FECHA_ATENCION_TS), DATE(c.NAC_FECHA), YEAR)
    END AS EDAD_HOMOLOGADA,
    onco.LOCALIZACION_ANATOMICA,
    -- Guardamos el TS para no recalcular en el siguiente SELECT
    --p.FECHA_ATENCION_TS
  FROM base b
  LEFT JOIN prefa p
    ON b.encuentro_norm = p.num_enc_norm
  LEFT JOIN clientes c
    ON CAST(b.CODIGO_CLIENTE AS STRING) = c.CODIGO_CLIENTE
  LEFT JOIN `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.MAESTRO_CIE10_DIAGNOSTICOS` onco  -- Agregado 15/09/2025 a pedido de Irpiri para localización anatomica
    ON UPPER(TRIM(p.COD_DIAGNOSTICO_01)) = UPPER(TRIM(onco.ICD_COD)) -- Agregado 15/09/2025 a pedido de Irpiri
   AND onco.APLICA = "S"  -- Agregado 15/09/2025 a pedido de Irpiri
  WHERE p.COD_SEDE IN ('1','2')   -- Agregado 15/09/2025 a pedido de Irpiri solo para sede lima y san borja
)

-- Select final (agregamos los rangos usando EDAD_HOMOLOGADA)
SELECT

  -- CAMPOS DE PROTOCOLO
  HOJA_PROT_PK,
  CODIGO_CLIENTE,
  ENCUENTRO_PROTOCOLO,
  CODIGO_PROTOCOLO,
  PROTOCOLO AS NOMBRE_ESQUEMA_TERAPEUTICO,
  CODIGO_DIAGNOSTICO,
  DIAGNOSTICO,
  ESTADO_PROTOCOLO,
  FECHA_INICIO_PROTOCOLO,
  FECHA_FIN_PROTOCOLO,
  FECHA_HORA_REGISTRO,

  -- CAMPOS DE CICLO-SESIONES
  PRES_CICLO_PK,
  CICLO,
  PRES_SESION_CAB_PK,
  NUMERO_SESION,
  ENCUENTRO_SESION,
  ESTADO_SESION,
  DESTINO,
  RECURSO,
  TIEMPO_ESTIMADO,
  FECHA_PREVISTA,
  FECHA_HORA_PROGRAMADA,

  -- CAMPOS DE TAREAS
  PRES_SESION_DET_PK,
  NRO_TAREA,
  TAREA,
  TIPO_TAREA,
  DURACION,
  ESTADO_TAREA,
  FECHA_HORA_RECEP_FARMACIA,
  FECHA_HORA_INICIO,
  FECHA_HORA_FIN,
  FECHA_HORA_DEVOL_FARMACIA,
  OBSERVACIONES,

  -- ===== CAMPOS ADICIONALES DE OD_PREFACTURA =====
  NUM_ENCUENTRO,
  COD_PACIENTE,
  NOM_PACIENTE,
  NOM_APELL_PATERNO_PCTE,
  NOM_APELL_MATERNO_PCTE,
  NOM_COMPLETO,
  FECHA_ATENCION,
  COD_GRUPO_ESPECIALIDAD,
  DES_GRUPO_ESPECIALIDAD,
  COD_SERVICIO,
  DES_SERVICIO,

  COD_TIPO_CITA,
  DES_TIPO_CITA,
  COD_ORIGEN_ATENCION,
  DES_ORIGEN_ATENCION,
  COD_MOTIVO_ING_ENC,
  DES_MOTIVO_ING_ENC,
  COD_UNIDAD_NEGOCIO,
  DES_UNIDAD_NEGOCIO,
  AMBITO_HOMOLOGADO,                            -- (homologado)

  COD_DIAGNOSTICO_01,
  DES_DIAGNOSTICO_01,
  COD_DIAGNOSTICO_02,
  DES_DIAGNOSTICO_02,
  COD_DIAGNOSTICO_03,
  DES_DIAGNOSTICO_03,

  COD_MEDICO,
  NOM_MEDICO,
  NOM_SEDE,

  -- ===== PROVIENE DE LEFT JOIN ENTRE CODIGO DIAGNOSTICO CON MAESTRIO DE CIE10 =====
  LOCALIZACION_ANATOMICA, -- AGREGADO 15/09/2025 a pedido ed Irpiri

  -- ===== EDAD Y RANGOS =====
  SEXO,
  EDAD_HOMOLOGADA,
  CASE
    WHEN EDAD_HOMOLOGADA BETWEEN 0  AND 11 THEN 'Infancia [0-11 años]'
    WHEN EDAD_HOMOLOGADA BETWEEN 12 AND 18 THEN 'Adolescencia [12-18 años]'
    WHEN EDAD_HOMOLOGADA BETWEEN 19 AND 29 THEN 'Juventud [19-29 años]'
    WHEN EDAD_HOMOLOGADA BETWEEN 30 AND 59 THEN 'Adultez [30-59 años]'
    WHEN EDAD_HOMOLOGADA >= 60            THEN 'Vejez [60 a + años]'
    ELSE 'Desconocido'
  END AS RANGO_ETARIO,

  CASE
    WHEN EDAD_HOMOLOGADA BETWEEN 0  AND 9   THEN '0 - 9'
    WHEN EDAD_HOMOLOGADA BETWEEN 10 AND 19  THEN '10 - 19'
    WHEN EDAD_HOMOLOGADA BETWEEN 20 AND 29  THEN '20 - 29'
    WHEN EDAD_HOMOLOGADA BETWEEN 30 AND 39  THEN '30 - 39'
    WHEN EDAD_HOMOLOGADA BETWEEN 40 AND 49  THEN '40 - 49'
    WHEN EDAD_HOMOLOGADA BETWEEN 50 AND 59  THEN '50 - 59'
    WHEN EDAD_HOMOLOGADA BETWEEN 60 AND 69  THEN '60 - 69'
    WHEN EDAD_HOMOLOGADA BETWEEN 70 AND 79  THEN '70 - 79'
    WHEN EDAD_HOMOLOGADA BETWEEN 80 AND 89  THEN '80 - 89'
    WHEN EDAD_HOMOLOGADA BETWEEN 90 AND 99  THEN '90 - 99'
    WHEN EDAD_HOMOLOGADA >= 100             THEN '100+'
    ELSE 'Desconocido'
  END AS RANGO_ETARIO_10_ANIOS,

  -- ===== FH ULTIMA ACTUALIZACION PARA VER EN LOOKER LA FECHA DE ACTUALIZACION DE LOS DATOS =====

   FORMAT_DATETIME('%Y-%m-%d %H:%M', CURRENT_DATETIME('America/Lima')) AS FH_ULTIMA_ACTUALIZACION

FROM joined;
