CREATE OR REPLACE VIEW `ci-datalake-dev.ci_dtlk_bqd_access_dev.VW_QUIMIOTERAPIA_ESQUEMAS_SESION_TAREAS` AS

/* ========================== KPI 9: PREESCRITOS ========================== */
/* Def.: AMBITO_HOMOLOGADO='Ambulatorio' AND ESTADO_PROTOCOLO='Planificado'
         FECHA_DT: FECHA_INICIO_PROTOCOLO (DD/MM/YYYY)
         KEY  : HOJA_PROT_PK
*/
SELECT

  -- FLAG DE KPI -- 
  'PREESCRITOS' AS KPI_NOMBRE,

  --CAMPOS DE FECHA_DT GLOBALES
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO))                                   AS FECHA_DT,
  EXTRACT(YEAR  FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO)))               AS ANIO,
  EXTRACT(MONTH FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO)))               AS MES,
  FORMAT_DATE('%Y-%m', SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO)))             AS ANIO_MES,

  --PROTOCOLO
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO))                                   AS FECHA_INICIO_PROTOCOLO_DT,
  -- SESION
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA))                                           AS FECHA_PREVISTA_DT,
  -- TAREA
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_HORA_INICIO))                                        AS FECHA_HORA_INICIO_DT,

  -- KEY (CONTEO POR EL CUAL SE VA RALIZAR EL COUNT DISTINC - DEPENDE DEL KPI)

  CAST(HOJA_PROT_PK AS STRING) AS KEY,
  CAST(NULL AS STRING)         AS NUM_KEY,                            -- no aplica para este KPI


  -- COLUMNAS ADICIONALES DE INTERES
  -- PROTOCOLO
  CAST(HOJA_PROT_PK AS STRING)         AS HOJA_PROT_PK,
  TRIM(DIAGNOSTICO)                    AS DIAGNOSTICO_PROTOCOLO,
  TRIM(CAST(CODIGO_CLIENTE AS STRING)) AS CODIGO_CLIENTE_PROTOCOLO,
  TRIM(NOMBRE_ESQUEMA_TERAPEUTICO)     AS NOMBRE_ESQUEMA_TERAPEUTICO,
  TRIM(ESTADO_PROTOCOLO)               AS ESTADO_PROTOCOLO,
  -- CICLO - SESION
  CAST(PRES_SESION_CAB_PK AS STRING)   AS PRES_SESION_CAB_PK,
  TRIM(ESTADO_SESION)                  AS ESTADO_SESION,
  TRIM(TIEMPO_ESTIMADO)                AS TIEMPO_ESTIMADO,
  CASE
  WHEN REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') IS NULL THEN NULL
  WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') AS INT64) < 240 THEN 'CORTA (<4h)'  
  WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') AS INT64) BETWEEN 240 AND 360 THEN 'MEDIANA (4-6h)'
  WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') AS INT64) > 360 THEN 'LARGA (>6h)'
  END                                  AS CLASIFICACION_DURACION_QUIMIOTERAPIA,
  -- TAREA
  TRIM(ESTADO_TAREA)                   AS ESTADO_TAREA,
  
  ------------------------
  -- CAMPOS CALCULADOS ADICIONALES - PEDIDO JAVIE 09/09/2023
  -- 1) Min → horas decimales
  ROUND(CAST(SAFE_CAST(REGEXP_EXTRACT(TRIM(TIEMPO_ESTIMADO), '([0-9]+)') AS INT64) AS NUMERIC) / 60,1) AS TIEMPO_ESTIMADO_EN_HORAS,


  -- 2) Flag > 18 horas
  CASE WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'([0-9]+)') AS INT64) > 18*60
       THEN 1 ELSE 0 END
    AS TIEMPO_ESTIMADO_MAYOR_18_HORAS,

  ------------------------

  /* ===== FILTROS PRESTACIONALES / DIMENSIONES ===== */
  NUM_ENCUENTRO,
  COD_PACIENTE,
  NOM_PACIENTE,
  SEXO,
  NOM_APELL_PATERNO_PCTE,
  NOM_APELL_MATERNO_PCTE,
  NOM_COMPLETO,
  FECHA_ATENCION,
  COD_GRUPO_ESPECIALIDAD,
  DES_GRUPO_ESPECIALIDAD,
  COD_SERVICIO,
  DES_SERVICIO,
  COD_TIPO_CITA,
  DES_TIPO_CITA,
  COD_ORIGEN_ATENCION,
  DES_ORIGEN_ATENCION,
  COD_MOTIVO_ING_ENC,
  DES_MOTIVO_ING_ENC,
  COD_UNIDAD_NEGOCIO,
  DES_UNIDAD_NEGOCIO,
  AMBITO_HOMOLOGADO,
  COD_DIAGNOSTICO_01,
  DES_DIAGNOSTICO_01,
  COD_DIAGNOSTICO_02,
  DES_DIAGNOSTICO_02,
  COD_DIAGNOSTICO_03,
  DES_DIAGNOSTICO_03,
  COD_MEDICO,
  NOM_MEDICO,
  NOM_SEDE,
  LOCALIZACION_ANATOMICA, -- Agregado 15/09/2025 a pedido de Irpiri
  EDAD_HOMOLOGADA,
  RANGO_ETARIO,
  RANGO_ETARIO_10_ANIOS,
  FH_ULTIMA_ACTUALIZACION
FROM `ci-datalake-dev.ci_dtlk_bqd_access_dev.TBL_ONCO_PROTOCOLO_PREFACTURA`
WHERE 
  TRIM(ESTADO_PROTOCOLO)  = 'Planificado'

  -- COMENTADO: AND TRIM(AMBITO_HOMOLOGADO)  = 'Ambulatorio' 
  -- En el Diccionario aparece “Ambulatorio”.  
  -- Irpiri indica que no debe hacerse esta distinción,  
  -- es decir, debe considerarse como “Ambulatorio + Hospitalario”.

  --AND TRIM(AMBITO_HOMOLOGADO) = 'Ambulatorio'
  
  AND HOJA_PROT_PK IS NOT NULL
  AND SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO)) IS NOT NULL

UNION ALL

/* ======================== KPI 10: ADMINISTRADOS ========================= */
/* Def.: AMBITO_HOMOLOGADO='Ambulatorio' AND ESTADO_SESION='Realizada'
         FECHA_DT: FECHA_PREVISTA (DD/MM/YYYY)
         KEY  : PRES_SESION_CAB_PK
*/
SELECT
  -- FLAG DE KPI -- 
  'ADMINISTRADOS' AS KPI_NOMBRE,

  --CAMPOS DE FECHA_DT GLOBALES
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA))                                         AS FECHA_DT,
  EXTRACT(YEAR  FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                     AS ANIO,
  EXTRACT(MONTH FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                     AS MES,
  FORMAT_DATE('%Y-%m', SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                   AS ANIO_MES,

  --PROTOCOLO
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO))                                   AS FECHA_INICIO_PROTOCOLO_DT,
  -- SESION
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA))                                           AS FECHA_PREVISTA_DT,
  -- TAREA
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_HORA_INICIO))                                        AS FECHA_HORA_INICIO_DT,

  -- KEY (CONTEO POR EL CUAL SE VA RALIZAR EL COUNT DISTINC - DEPENDE DEL KPI)
  CAST(PRES_SESION_CAB_PK AS STRING) AS KEY,
  CAST(NULL AS STRING)               AS NUM_KEY,                        -- no aplica

   -- COLUMNAS ADICIONALES DE INTERES
  -- PROTOCOLO
  CAST(HOJA_PROT_PK AS STRING)         AS HOJA_PROT_PK,
  TRIM(DIAGNOSTICO)                    AS DIAGNOSTICO_PROTOCOLO,
  TRIM(CAST(CODIGO_CLIENTE AS STRING)) AS CODIGO_CLIENTE_PROTOCOLO,
  TRIM(NOMBRE_ESQUEMA_TERAPEUTICO)     AS NOMBRE_ESQUEMA_TERAPEUTICO,
  TRIM(ESTADO_PROTOCOLO)               AS ESTADO_PROTOCOLO,
  -- CICLO - SESION
  CAST(PRES_SESION_CAB_PK AS STRING)   AS PRES_SESION_CAB_PK,
  TRIM(ESTADO_SESION)                  AS ESTADO_SESION,
  TRIM(TIEMPO_ESTIMADO)                AS TIEMPO_ESTIMADO,
  CASE
  WHEN REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') IS NULL THEN NULL
  WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') AS INT64) < 240 THEN 'CORTA (<4h)'  
  WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') AS INT64) BETWEEN 240 AND 360 THEN 'MEDIANA (4-6h)'
  WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') AS INT64) > 360 THEN 'LARGA (>6h)'
  END              
                      AS CLASIFICACION_DURACION_QUIMIOTERAPIA,
  -- TAREA
  TRIM(ESTADO_TAREA)                   AS ESTADO_TAREA,
  
    ------------------------
  -- CAMPOS CALCULADOS ADICIONALES - PEDIDO JAVIE 09/09/2023
  -- 1) Min → horas decimales
  ROUND(CAST(SAFE_CAST(REGEXP_EXTRACT(TRIM(TIEMPO_ESTIMADO), '([0-9]+)') AS INT64) AS NUMERIC) / 60,1) AS TIEMPO_ESTIMADO_EN_HORAS,


  -- 2) Flag > 18 horas
  CASE WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'([0-9]+)') AS INT64) > 18*60
       THEN 1 ELSE 0 END
    AS TIEMPO_ESTIMADO_MAYOR_18_HORAS,
  ------------------------

  /* ===== FILTROS PRESTACIONALES / DIMENSIONES ===== */
  NUM_ENCUENTRO,
  COD_PACIENTE,
  NOM_PACIENTE,
  SEXO,
  NOM_APELL_PATERNO_PCTE,
  NOM_APELL_MATERNO_PCTE,
  NOM_COMPLETO,
  FECHA_ATENCION,
  COD_GRUPO_ESPECIALIDAD,
  DES_GRUPO_ESPECIALIDAD,
  COD_SERVICIO,
  DES_SERVICIO,
  COD_TIPO_CITA,
  DES_TIPO_CITA,
  COD_ORIGEN_ATENCION,
  DES_ORIGEN_ATENCION,
  COD_MOTIVO_ING_ENC,
  DES_MOTIVO_ING_ENC,
  COD_UNIDAD_NEGOCIO,
  DES_UNIDAD_NEGOCIO,
  AMBITO_HOMOLOGADO,
  COD_DIAGNOSTICO_01,
  DES_DIAGNOSTICO_01,
  COD_DIAGNOSTICO_02,
  DES_DIAGNOSTICO_02,
  COD_DIAGNOSTICO_03,
  DES_DIAGNOSTICO_03,
  COD_MEDICO,
  NOM_MEDICO,
  NOM_SEDE,
  LOCALIZACION_ANATOMICA, -- Agregado 15/09/2025 a pedido de Irpiri
  EDAD_HOMOLOGADA,
  RANGO_ETARIO,
  RANGO_ETARIO_10_ANIOS,
  FH_ULTIMA_ACTUALIZACION
FROM `ci-datalake-dev.ci_dtlk_bqd_access_dev.TBL_ONCO_PROTOCOLO_PREFACTURA`
WHERE 

  -- COMENTADO: AND TRIM(AMBITO_HOMOLOGADO)  = 'Ambulatorio' 
  -- En el Diccionario aparece “Ambulatorio”.  
  -- Irpiri indica que no debe hacerse esta distinción,  
  -- es decir, debe considerarse como “Ambulatorio + Hospitalario”.
  --TRIM(AMBITO_HOMOLOGADO) = 'Ambulatorio' AND

   TRIM(ESTADO_SESION)     = 'Realizada'
  AND PRES_SESION_CAB_PK IS NOT NULL
  AND SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)) IS NOT NULL

UNION ALL

/* = KPI 11: % ADMINISTRADOS SEGÚN PLANIFICACIÓN ========================= */
/* Denominador: NRO_TAREA=1 AND ESTADO_TAREA='Realizado' AND AMBITO_HOMOLOGADO='Ambulatorio'
   Numerador  : (denominador) + ESTADO_SESION='Realizada' AND DATE(FECHA_HORA_INICIO)=FECHA_PREVISTA
   FECHA_DT      : FECHA_PREVISTA (DD/MM/YYYY)
   KEY        : PRES_SESION_CAB_PK  (denominador)
   NUM_KEY    : PRES_SESION_CAB_PK  (solo si cumple numerador; si no, NULL)
*/
SELECT
  -- FLAG DE KPI -- 
  'ADHERIDOS' AS KPI_NOMBRE,

  --CAMPOS DE FECHA_DT GLOBALES
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA))                                         AS FECHA_DT,
  EXTRACT(YEAR  FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                     AS ANIO,
  EXTRACT(MONTH FROM SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                     AS MES,
  FORMAT_DATE('%Y-%m', SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)))                   AS ANIO_MES,

    --PROTOCOLO
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_INICIO_PROTOCOLO))                                   AS FECHA_INICIO_PROTOCOLO_DT,
  -- SESION
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA))                                           AS FECHA_PREVISTA_DT,
  -- TAREA
  SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_HORA_INICIO))                                        AS FECHA_HORA_INICIO_DT,

  -- KEY (COUNT DISTINC - PARA ESTE KPI FUNCIONA COMO DENOMINADOR)
  -- DETALLE: EN looker agregar CAMPO CALULADO: DENOMINADOR: COUNT_DISTINCT(KEY) o tambien COUNT_DISTINCT(PRES_SESION_CAB_PK)
  CAST(PRES_SESION_CAB_PK AS STRING) AS KEY,   

  -- NUM_KEY: COUNT DISTINC - PARA ESTE KPI FUNCIONA COMO NUMERADOR 
  -- DETALLE: EN looker agregar CAMPO CALULADO: NUMERADOR: COUNT_DISTINCT(NUM_KEY) 
  IF(
    TRIM(ESTADO_SESION) = 'Realizada'
    AND DATE(SAFE.PARSE_DATETIME('%d/%m/%Y %H:%M:%S', TRIM(FECHA_HORA_INICIO))) =
        SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)),
    CAST(PRES_SESION_CAB_PK AS STRING), NULL
  ) AS NUM_KEY,

  -------------------------------------
  -- En caso de este KPI para hallar el porcentraje crear un cmapo calculado en looker
  -- detalle campo calcualdor: KPI11 = COUNT_DISTINCT(NUM_KEY) / COUNT_DISTINCT(KEY)
  -------------------------------------

  -- COLUMNAS ADICIONALES DE INTERES

  -- PROTOCOLO
  CAST(HOJA_PROT_PK AS STRING)         AS HOJA_PROT_PK,
  TRIM(DIAGNOSTICO)                    AS DIAGNOSTICO_PROTOCOLO,
  TRIM(CAST(CODIGO_CLIENTE AS STRING)) AS CODIGO_CLIENTE_PROTOCOLO,
  TRIM(NOMBRE_ESQUEMA_TERAPEUTICO)     AS NOMBRE_ESQUEMA_TERAPEUTICO,
  TRIM(ESTADO_PROTOCOLO)               AS ESTADO_PROTOCOLO,
  -- CICLO - SESION
  CAST(PRES_SESION_CAB_PK AS STRING)   AS PRES_SESION_CAB_PK,
  TRIM(ESTADO_SESION)                  AS ESTADO_SESION,
  TRIM(TIEMPO_ESTIMADO)                AS TIEMPO_ESTIMADO,
  CASE
  WHEN REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') IS NULL THEN NULL
  WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') AS INT64) < 240 THEN 'CORTA (<4h)'  
  WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') AS INT64) BETWEEN 240 AND 360 THEN 'MEDIANA (4-6h)'
  WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'(\d+)') AS INT64) > 360 THEN 'LARGA (>6h)'
  END                                  AS CLASIFICACION_DURACION_QUIMIOTERAPIA,
  -- TAREA
  TRIM(ESTADO_TAREA)                   AS ESTADO_TAREA,
  
    ------------------------
  -- CAMPOS CALCULADOS ADICIONALES - PEDIDO JAVIE 09/09/2023
  -- 1) Min → horas decimales
  ROUND(CAST(SAFE_CAST(REGEXP_EXTRACT(TRIM(TIEMPO_ESTIMADO), '([0-9]+)') AS INT64) AS NUMERIC) / 60,1) AS TIEMPO_ESTIMADO_EN_HORAS,

  -- 2) Flag > 18 horas
  CASE WHEN SAFE_CAST(REGEXP_EXTRACT(TIEMPO_ESTIMADO, r'([0-9]+)') AS INT64) > 18*60
       THEN 1 ELSE 0 END
    AS TIEMPO_ESTIMADO_MAYOR_18_HORAS,


  ------------------------

  /* ===== FILTROS PRESTACIONALES / DIMENSIONES ===== */
  NUM_ENCUENTRO,
  COD_PACIENTE,
  NOM_PACIENTE,
  SEXO,
  NOM_APELL_PATERNO_PCTE,
  NOM_APELL_MATERNO_PCTE,
  NOM_COMPLETO,
  FECHA_ATENCION,
  COD_GRUPO_ESPECIALIDAD,
  DES_GRUPO_ESPECIALIDAD,
  COD_SERVICIO,
  DES_SERVICIO,
  COD_TIPO_CITA,
  DES_TIPO_CITA,
  COD_ORIGEN_ATENCION,
  DES_ORIGEN_ATENCION,
  COD_MOTIVO_ING_ENC,
  DES_MOTIVO_ING_ENC,
  COD_UNIDAD_NEGOCIO,
  DES_UNIDAD_NEGOCIO,
  AMBITO_HOMOLOGADO,  -- No proviene de Formulario sino de DES_UNIDAD_NEGOCIO
  COD_DIAGNOSTICO_01,
  DES_DIAGNOSTICO_01,
  COD_DIAGNOSTICO_02,
  DES_DIAGNOSTICO_02,
  COD_DIAGNOSTICO_03,
  DES_DIAGNOSTICO_03,
  COD_MEDICO,
  NOM_MEDICO,
  NOM_SEDE,
  LOCALIZACION_ANATOMICA, -- Agregado 15/09/2025 a pedido de Irpiri
  EDAD_HOMOLOGADA,
  RANGO_ETARIO,
  RANGO_ETARIO_10_ANIOS,
  FH_ULTIMA_ACTUALIZACION
FROM `ci-datalake-dev.ci_dtlk_bqd_access_dev.TBL_ONCO_PROTOCOLO_PREFACTURA`
WHERE 
  SAFE_CAST(TRIM(CAST(NRO_TAREA AS STRING)) AS INT64) = 1
  AND  TRIM(ESTADO_SESION) = 'Realizada'
  AND TRIM(ESTADO_TAREA)   = 'Realizado'

  -- COMENTADO: AND TRIM(AMBITO_HOMOLOGADO)  = 'Ambulatorio' 
  -- En el Diccionario aparece “Ambulatorio”.  
  -- Irpiri indica que no debe hacerse esta distinción,  
  -- es decir, debe considerarse como “Ambulatorio + Hospitalario”.

  --AND TRIM(AMBITO_HOMOLOGADO)  = 'Ambulatorio' 

  AND PRES_SESION_CAB_PK IS NOT NULL
  AND SAFE.PARSE_DATE('%d/%m/%Y', TRIM(FECHA_PREVISTA)) IS NOT NULL
;
