CREATE OR REPLACE TABLE `ci-datalake-dev.ci_dtlk_bqd_access_dev.TMP_KPI1_ONCOLOGIA_DE_MAMA` AS
WITH fase1 AS (
  SELECT *
  FROM (
    SELECT 
      f1.DNI,
      f1.EPISODIO,
      p1.COD_GARANTE_AGRUP,
      p1.NOM_GARANTE_AGRUP,
      f1.SERVICIO_INGRESO        AS ESPECIALIDAD_IN,
      f1.SERVICIO_ATENCION       AS ESPECIALIDAD,
      f1.SEDE                    AS NOM_SEDE,
      f1.CODIGO_CLIENTE,
      f1.PACIENTE,
      f1.FECHA_NACIMIENTO_PACIENTE,
      f1.EDAD_PACIENTE,
      f1.EDAD_GRUPO,
      f1.TIPO_EPISODIO,
      f1.FECHA_SOLIC_EXAM,
      f1.CLASE_PRUEBA,
      f1.CODIGO_PRUEBA,
      f1.NOMBRE_PRUEBA,
      f1.ESTADO_PK,
      f1.ESTADO_DESC,
      DATE(f1.FH_INFORME_FINALIZADO) AS FH_INFORME_FINALIZADO,
      f1.BIRAD_INFORME,
      ROW_NUMBER() OVER (
        PARTITION BY f1.DNI
        ORDER BY DATE(f1.FH_INFORME_FINALIZADO) ASC
      ) AS rn_f1
    FROM `ci-datalake-dev.ci_dtlk_bqd_access_dev.TBL_ONCOLOGIA_MAMA_FASE1_MAMOGRAFIA` f1
    INNER JOIN `ci-datalake-prod.ci_dtlk_bqd_staging_prod.OD_PREFACTURA` p1
      ON CAST(f1.EPISODIO AS STRING) = CAST(p1.NUM_ENCUENTRO AS STRING)
    WHERE f1.BIRAD_INFORME IN ('BIRAD4','BIRAD5')
      AND f1.ESTADO_DESC = 'Finalizada sin revisar'
      AND f1.FH_INFORME_FINALIZADO IS NOT NULL
  )
  WHERE rn_f1 = 1   -- primera mamografía por paciente
),

fase2 AS (
  SELECT
    f2.DNI_PCTE AS DNI,
    DATE(f2.FCH_COMUNICACION_ALERTA) AS FCH_COMUNICACION_ALERTA,
    f2.TIPO_MUESTRA_PRUEBA
  FROM `ci-datalake-dev.ci_dtlk_bqd_access_dev.TBL_ONCOLOGIA_MAMA_FASE2_ALERTA_POSITIVO` f2
  WHERE f2.FCH_COMUNICACION_ALERTA IS NOT NULL
),

pares AS (
  SELECT
    f1.*,
    f2.FCH_COMUNICACION_ALERTA,
    f2.TIPO_MUESTRA_PRUEBA,
    DATE_DIFF(f2.FCH_COMUNICACION_ALERTA, f1.FH_INFORME_FINALIZADO, DAY) AS dias_diff,
    ROW_NUMBER() OVER (
      PARTITION BY f1.DNI
      ORDER BY f2.FCH_COMUNICACION_ALERTA ASC
    ) AS rn
  FROM fase1 f1
  JOIN fase2 f2
    ON f1.DNI = f2.DNI
   AND f2.FCH_COMUNICACION_ALERTA >= f1.FH_INFORME_FINALIZADO
),

final AS (
  SELECT
    'MAMOGRAFIA_A_BIOPSIA' AS kpi_nombre,
    28 AS meta_dias,
    EXTRACT(YEAR  FROM FCH_COMUNICACION_ALERTA) AS anio,
    EXTRACT(MONTH FROM FCH_COMUNICACION_ALERTA) AS mes,
    FORMAT_DATE('%Y-%m', FCH_COMUNICACION_ALERTA) AS anio_mes,
    DNI,
    EDAD_PACIENTE,
    EDAD_GRUPO,
    FH_INFORME_FINALIZADO,
    FCH_COMUNICACION_ALERTA,
    CAST(NULL AS DATE)   AS FEH_CITA,
    CAST(NULL AS DATE)   AS FCH_TRATAMIENTO_QUIRURGICO,
    CAST(NULL AS DATE)   AS FCH_TRATAMIENTO_NO_QUIRURGICO,
    CAST(NULL AS STRING) AS DX_QUIRURGICO,
    CAST(NULL AS STRING) AS TIPO_TRATAMIENTO_NO_QUIRURGICO,
    UPPER(NOM_SEDE)      AS NOM_SEDE,
    NOM_GARANTE_AGRUP,
    COD_GARANTE_AGRUP,
    COALESCE(ESPECIALIDAD, ESPECIALIDAD_IN) AS ESPECIALIDAD,
    dias_diff,
    CURRENT_DATETIME('America/Lima') AS FH_ULTIMA_ACTUALIZACION,
    TIPO_MUESTRA_PRUEBA
  FROM pares
  WHERE rn = 1   -- primera alerta posterior a la primera mamografía
)

SELECT * FROM final;
