CREATE OR REPLACE TABLE `ci-datalake-dev.ci_dtlk_bqd_business_dev.TBL_PACIENTES_ONCOLOGIA` AS
SELECT DISTINCT
  -- Encuentro
  CAST(PRE.NUM_ENCUENTRO AS STRING) AS NUM_ENCUENTRO,

  -- Paciente
  CAST(PRE.COD_PACIENTE AS STRING) AS COD_PACIENTE,
  PRE.NOM_PACIENTE,
  PRE.NOM_APELL_PATERNO_PCTE,
  PRE.NOM_APELL_MATERNO_PCTE,

  -- Nombre completo
  CONCAT(
    COALESCE(TRIM(PRE.NOM_PACIENTE), ''), ' ',
    COALESCE(TRIM(PRE.NOM_APELL_PATERNO_PCTE), ''), ' ',
    COALESCE(TRIM(PRE.NOM_APELL_MATERNO_PCTE), '')
  ) AS NOM_COMPLETO,

  -- Fecha de atención
  FORMAT_TIMESTAMP('%d/%m/%Y', PRE.FEH_PREFACTURA) AS FECHA_ATENCION,

  -- Grupo especialidad O ESPCIALIDAD
  PRE.COD_GRUPO_ESPECIALIDAD,
  PRE.DES_GRUPO_ESPECIALIDAD,

--   ONCO.COD_GRUPO_ESPECIALIDAD AS COD_GRUPO_ESPECIALIDAD_ONCO,
--   ONCO.DES_GRUPO_ESPECIALIDAD AS DES_GRUPO_ESPECIALIDAD_ONCO,
  
    -- Especialidad O SERVICIO
  PRE.COD_ESPECIALIDAD AS COD_SERVICIO,
  PRE.DES_ESPECIALIDAD AS DES_SERVICIO,
--   ONCO.CODIGO_SERVICIO AS COD_SERVICIO_ONCO,
--   ONCO.SERVICIO        AS DES_SERVICIO_ONCO,
--   ONCO.FLG_STATUT_ACTIF AS FLG_STATUT_ACTIF_ONCO,
-- 
-- LOCALIZACION ANATOMICA
--ONCO.LOCALIZACION_ANATOMICA,  -- AGREGADO 15/09/2025 A PEDIDO DE IRPIRI


--adiconales
  PRE.COD_TIPO_CITA,
PRE.DES_TIPO_CITA,
PRE.COD_ORIGEN_ATENCION,
PRE.DES_ORIGEN_ATENCION,
PRE.COD_MOTIVO_ING_ENC,
PRE.DES_MOTIVO_ING_ENC,
PRE.COD_UNIDAD_NEGOCIO,
PRE.DES_UNIDAD_NEGOCIO,
PRE.COD_DIAGNOSTICO_01, -- DIAGNOSTICO 
PRE.DES_DIAGNOSTICO_01,
PRE.COD_DIAGNOSTICO_02,
PRE.DES_DIAGNOSTICO_02,
PRE.COD_DIAGNOSTICO_03,
PRE.DES_DIAGNOSTICO_03,
--fin adiconales

  -- Especialidad
  --PRE.COD_ESPECIALIDAD,
  --PRE.DES_ESPECIALIDAD,

  -- Médico
  PRE.COD_MEDICO,
  PRE.NOM_MEDICO,

  -- Sede
  PRE.NOM_SEDE

FROM `ci-datalake-prod.ci_dtlk_bqd_staging_prod.OD_PREFACTURA` AS PRE
INNER JOIN `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.MAESTRO_CIE10_DIAGNOSTICOS` AS ONCO
  ON UPPER(TRIM(PRE.COD_DIAGNOSTICO_01)) = UPPER(TRIM(ONCO.ICD_COD))
--  AND onco.APLICA = "S"

WHERE SAFE_CAST(PRE.NUM_ENCUENTRO AS INT64) IS NOT NULL
and  PRE.COD_SEDE IN ('1','2')
; -- agregado 15/09/2025 a pedido de Irpiri codigos solo para Lima y San Borja
