CREATE OR REPLACE TABLE `ci-datalake-dev.ci_dtlk_bqd_business_dev.PACIENTES_ONCOLOGIA_PREST_FORM_QUIMIOTERAPIA` AS

SELECT DISTINCT
  -- Todas las columnas de la tabla base (paciente prestacional)
  TB4.*,

  -- Columnas específicas del formulario
  d.EPIS_PK,
  --d.TIPO_ENCUENTRO,
  d.AMBITO,
  d.CENTRO,
  d.FECHA_ACTUAL,
  d.N_DOCUMENTO,
  d.PACIENTE,
  d.SEXO,
  d.EDAD_ANO_MES_DIA,
  d.TIPO_PACIENTE,
  d.HORA_INICIO_QUIMIOTERAPIA,
  d.HORA_TERMINO_QUIMIOTERAPIA,
  d.NOMBRE_ESQUEMA_TERAPEUTICO,
  d.DIAGNOSTICO_ESQUEMA_QUIMIOTERAPIA,
  d.ADMINISTRACION_ESQUEMA_TERAPEUTICO

FROM `ci-datalake-dev.ci_dtlk_bqd_business_dev.TBL_PACIENTES_ONCOLOGIA` AS TB4

--LEFT JOIN `ci-datalake-dev.test_dataset.FORMULARIO_PLAN_MEDICO_ONCOLOGICO` AS d  
LEFT JOIN `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.FORM_ADMINISTRACION_QUIMIOTERAPIA_ENFERMERIA` AS d  
  ON TB4.NUM_ENCUENTRO = CAST(d.EPIS_PK AS STRING)

-- WHERE 
--  d.Tipo_de_paciente IS NOT NULL;
