CREATE OR REPLACE VIEW `ci-datalake-dev.ci_dtlk_bqd_business_dev.VW_PACIENTES_ONCO_PREST_FORM` AS
WITH src AS (
  SELECT
    --- COLUMNAS TABLAS PRESTACIONALES
    NUM_ENCUENTRO,
    COD_PACIENTE,
    NOM_PACIENTE,
    NOM_APELL_PATERNO_PCTE,
    NOM_APELL_MATERNO_PCTE,
    NOM_COMPLETO,
    FECHA_ATENCION,
    COD_GRUPO_ESPECIALIDAD,
    DES_GRUPO_ESPECIALIDAD,
    -- COD_GRUPO_ESPECIALIDAD_ONCO,
    -- DES_GRUPO_ESPECIALIDAD_ONCO,
    COD_SERVICIO,
    DES_SERVICIO,
    -- COD_SERVICIO_ONCO,
    -- DES_SERVICIO_ONCO,
    -- FLG_STATUT_ACTIF_ONCO,
    COD_TIPO_CITA,
    DES_TIPO_CITA,
    COD_ORIGEN_ATENCION,
    DES_ORIGEN_ATENCION,
    COD_MOTIVO_ING_ENC,
    DES_MOTIVO_ING_ENC,
    COD_UNIDAD_NEGOCIO,
    DES_UNIDAD_NEGOCIO,
    COD_DIAGNOSTICO_01,
    DES_DIAGNOSTICO_01,
    COD_DIAGNOSTICO_02,
    DES_DIAGNOSTICO_02,
    COD_DIAGNOSTICO_03,
    DES_DIAGNOSTICO_03,
    COD_MEDICO,
    NOM_MEDICO,
    NOM_SEDE,
    --- COLUMNAS FORMULARIOS QUIMIOTERAPIA
    EPIS_PK,
    --TIPO_ENCUENTRO,
    AMBITO,
    CENTRO,
    FECHA_ACTUAL,
    N_DOCUMENTO,
    PACIENTE,
    SEXO,
    EDAD_ANO_MES_DIA,
    TIPO_PACIENTE,
    HORA_INICIO_QUIMIOTERAPIA,
    HORA_TERMINO_QUIMIOTERAPIA,
    NOMBRE_ESQUEMA_TERAPEUTICO,
    DIAGNOSTICO_ESQUEMA_QUIMIOTERAPIA,
    ADMINISTRACION_ESQUEMA_TERAPEUTICO,
    --- COLUMNAS DE FORMULARIO DE QUIMIOTERAPIA HOMOLOGADOS
    FECHA_ATENCION_TS,
    FECHA_ACTUAL_TS,
    HORA_INICIO_QUIMIOTERAPIA_HOMOLOGADO, -- agregado 2/09/2025
    HORA_TERMINO_QUIMIOTERAPIA_HOMOLOGADO, -- agregado 2/09/2025
    DURACION_QUIMIOTERAPIA, -- agregado 2/09/2025
    CLASIFICACION_DURACION_QUIMIOTERAPIA, -- agregado 3/09/2025
    EDAD_HOMOLOGADA,
    RANGO_ETARIO,
    RANGO_ETARIO_10_ANIOS,
    TIPO_PACIENTE_HOMOLOGADO,
    AMBITO_HOMOLOGADO,
    FH_ULTIMA_ACTUALIZACION,
    -- PARA AGRUPACION POR AÑO Y MES
    EXTRACT(YEAR  FROM FECHA_ACTUAL_TS)  AS anio_utc,
    EXTRACT(MONTH FROM FECHA_ACTUAL_TS) AS mes_utc,

    -- NORMALIZACION DE DIAGNOSTICO
    REGEXP_REPLACE(UPPER(TRIM(DIAGNOSTICO_ESQUEMA_QUIMIOTERAPIA)), r'\s+', ' ') AS dx_norm,

    -- PRIORIDAD DE CATEGORIAS PARA TIPO PACIENTE
    CASE
      WHEN UPPER(TRIM(TIPO_PACIENTE_HOMOLOGADO)) = 'NUEVO' THEN 1
      WHEN UPPER(TRIM(TIPO_PACIENTE_HOMOLOGADO)) = 'CONTINUADOR' THEN 2
      WHEN UPPER(TRIM(TIPO_PACIENTE_HOMOLOGADO)) = 'USUARIO SIN TIPO PACIENTE' THEN 3
      ELSE 4
    END AS tipo_rank,

    -- FLAG DE NUEVO Y CONTINUADOR (válidos) POR ENCIAM DE NULL
    CASE
      WHEN UPPER(TRIM(TIPO_PACIENTE_HOMOLOGADO)) IN ('NUEVO','CONTINUADOR') THEN 0  -- válidos
      ELSE 1  -- null
    END AS es_sin_tipo_o_otro
  FROM `ci-datalake-dev.ci_dtlk_bqd_business_dev.PACIENTES_ONCOLOGIA_PREST_FORM_QUIMIOTERAPIA_HOMOLOGADO`
  WHERE
    FECHA_ACTUAL_TS >= TIMESTAMP("2025-05-01 00:00:00 UTC") -- mayores a abril , alcance 20/08/2025 Irpiri
    AND NULLIF(TRIM(DIAGNOSTICO_ESQUEMA_QUIMIOTERAPIA), '') IS NOT NULL
),
ranked AS (
  SELECT
    s.*,
    ROW_NUMBER() OVER (
      PARTITION BY
        s.COD_PACIENTE,
        s.anio_utc,
        s.mes_utc,
        s.dx_norm
      ORDER BY
        s.es_sin_tipo_o_otro ASC,  -- 1) primero tipos válidos (Nuevo/Continuador), luego Sin tipo (null)
        s.FECHA_ACTUAL_TS   ASC,   -- 2) dentro de ese grupo, la fecha más antigua
        s.tipo_rank         ASC    -- 3) si misma fecha/hora: Nuevo > Continuador > Sin tipo > otros
    ) AS rn
  FROM src s
)
SELECT
  --- COLUMNAS TABLAS PRESTACIONALES
  NUM_ENCUENTRO,
  COD_PACIENTE,
  NOM_PACIENTE,
  NOM_APELL_PATERNO_PCTE,
  NOM_APELL_MATERNO_PCTE,
  NOM_COMPLETO,
  FECHA_ATENCION,
  COD_GRUPO_ESPECIALIDAD,
  DES_GRUPO_ESPECIALIDAD,
  -- COD_GRUPO_ESPECIALIDAD_ONCO,
  -- DES_GRUPO_ESPECIALIDAD_ONCO,
  COD_SERVICIO,
  DES_SERVICIO,
  -- COD_SERVICIO_ONCO,
  -- DES_SERVICIO_ONCO,
  -- FLG_STATUT_ACTIF_ONCO,
  COD_TIPO_CITA,
  DES_TIPO_CITA,
  COD_ORIGEN_ATENCION,
  DES_ORIGEN_ATENCION,
  COD_MOTIVO_ING_ENC,
  DES_MOTIVO_ING_ENC,
  COD_UNIDAD_NEGOCIO,
  DES_UNIDAD_NEGOCIO,
  COD_DIAGNOSTICO_01,
  DES_DIAGNOSTICO_01,
  COD_DIAGNOSTICO_02,
  DES_DIAGNOSTICO_02,
  COD_DIAGNOSTICO_03,
  COD_MEDICO,
  NOM_MEDICO,
  NOM_SEDE,
  --- COLUMNAS FORMULARIOS QUIMIOTERAPIA
   EPIS_PK,
  --TIPO_ENCUENTRO,
  AMBITO,
  CENTRO,
  FECHA_ACTUAL,
  N_DOCUMENTO,
  PACIENTE,
  SEXO,
  EDAD_ANO_MES_DIA,
  TIPO_PACIENTE,
  HORA_INICIO_QUIMIOTERAPIA,
  HORA_TERMINO_QUIMIOTERAPIA,
  NOMBRE_ESQUEMA_TERAPEUTICO,
  DIAGNOSTICO_ESQUEMA_QUIMIOTERAPIA,
  ADMINISTRACION_ESQUEMA_TERAPEUTICO,
  --------------
  --- COLUMNAS DE FORMULARIO DE QUIMIOTERAPIA HOMOLOGADOS
   FECHA_ATENCION_TS,
   FECHA_ACTUAL_TS,
   HORA_INICIO_QUIMIOTERAPIA_HOMOLOGADO, -- agregado 2/09/2025
   HORA_TERMINO_QUIMIOTERAPIA_HOMOLOGADO, -- agregado 2/09/2025
   DURACION_QUIMIOTERAPIA, -- agregado 2/09/2025
    CLASIFICACION_DURACION_QUIMIOTERAPIA, -- agregado 3/09/2025

   EDAD_HOMOLOGADA,
   RANGO_ETARIO,
   RANGO_ETARIO_10_ANIOS,
   TIPO_PACIENTE_HOMOLOGADO,
   AMBITO_HOMOLOGADO,
   FH_ULTIMA_ACTUALIZACION,


FROM ranked
WHERE rn = 1