CREATE OR REPLACE TABLE `ci-datalake-dev.ci_dtlk_bqd_business_dev.PACIENTES_ONCOLOGIA_PREST_FORM_QUIMIOTERAPIA` AS
SELECT DISTINCT
  -- Todas las columnas de la tabla base (paciente prestacional)
  TB4.*,

  -- Columnas específicas del formulario
  d.EPIS_PK,
  d.AMBITO,
  d.CENTRO,
  d.FECHA_ACTUAL,
  d.N_DOCUMENTO,
  d.PACIENTE,
  d.SEXO,
  d.EDAD_ANO_MES_DIA,
  d.TIPO_PACIENTE,
  d.HORA_INICIO_QUIMIOTERAPIA,
  d.HORA_TERMINO_QUIMIOTERAPIA,
  d.NOMBRE_ESQUEMA_TERAPEUTICO,
  d.DIAGNOSTICO_ESQUEMA_QUIMIOTERAPIA,
  d.ADMINISTRACION_ESQUEMA_TERAPEUTICO,

  CASE 
    WHEN m.LOCALIZACION_ANATOMICA IS NULL 
      THEN 'NO ONCOLOGICO'
    ELSE m.LOCALIZACION_ANATOMICA
  END AS LOCALIZACION_ANATOMICA

FROM `ci-datalake-dev.ci_dtlk_bqd_business_dev.TBL_PACIENTES_ONCOLOGIA` AS TB4

LEFT JOIN `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.FORM_ADMINISTRACION_QUIMIOTERAPIA_ENFERMERIA` AS d
  ON TB4.NUM_ENCUENTRO = CAST(d.EPIS_PK AS STRING)

INNER JOIN `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.MAESTRO_CIE10_DIAGNOSTICOS` AS m
  ON SUBSTR(d.DIAGNOSTICO_ESQUEMA_QUIMIOTERAPIA, 1, 5) = m.ICD_COD
  AND m.APLICA = 'S';
